### ISSUE TITLE
Readme doesn't match reality

### ISSUE THREAD

**Issue by andybak** [Unity-Technologies/ProBuilder-API-Examples#1]
> See the Releases section to get a copy that matches your installed ProBuilder version.

Except "releases" is empty.

**Comment by karl-** [comment]
Thanks, I tagged the current version and drafted a release.

**Comment by andybak** [comment]
May since the last release. Are you sure removing that advice from the readme might not be a better plan going forward?

**Comment by karl-** [comment]
Agreed, it's removed. We're using branches to track internal versions now anyways.
