### ISSUE TITLE
Update documentation to increase clarity on API compatibility with package manager only 

### ISSUE THREAD

**Issue by zhenwei2972** [Unity-Technologies/ProBuilder-API-Examples#7]
Should this repo be updated with the new updated examples?

**Comment by andybak** [comment]
Here's the line in the readme:

> Example code for the Package Manager version of ProBuilder.

Is that sufficiently clear?

1. Will it always be in sync with package manager?
2. Is it synced with the release or preview version of Probuilder (if there is one)
3. Does the version of Probuilder in Package Manger differ depending on your Unity version? I know it does for other packages.

Would it be better to put an actual Probuilder version in the readme and update it when needed?

**Comment by zhenwei2972** [comment]
Hi Andy, thanks for the quick reply, first of all I'd like to apologize, opened the issue when I was unaware of the discrepancies between installing from the package manager and pulling from the asset store.  Hence raising the issue. 

That said I will test out whether the package manager pulls different versions of probuilder in accordance to different unity versions and update you.

Checked with 2018 LTS Unity, seems to be pulling the same version of 4.0.5, I believe the current approach is fine, not sure of any internal conventions, but would it be helpful to have a statement stating currently supported version?
